/* Kanji you actually need, in two groups:
     g:"sign" — what you have to read off a wall, door, or ticket machine in Japan
     g:"app"  — every kanji that appears 3+ times in this app's own scenes,
                sentence cards, and phrases, so your own lines become readable
   Fields: k kanji / on ON reading (katakana, the Chinese-derived one)
           kun KUN reading (hiragana, the native one; a dot marks the okurigana)
           en meaning / w example word / wk its kana / wg what the word means
   Readings are the ones you'll actually meet, not the full dictionary list. */
const KANJI=[
 /* --- doors, directions, and the words on the wall --- */
 {g:"sign",k:"入",on:"ニュウ",kun:"はい.る / い.れる",en:"enter, put in",w:"入口",wk:"いりぐち",wg:"entrance"},
 {g:"sign",k:"出",on:"シュツ",kun:"で.る / だ.す",en:"exit, go out, take out",w:"出口",wk:"でぐち",wg:"exit"},
 {g:"sign",k:"口",on:"コウ",kun:"くち",en:"mouth, opening",w:"改札口",wk:"かいさつぐち",wg:"ticket gate"},
 {g:"sign",k:"男",on:"ダン",kun:"おとこ",en:"man",w:"男",wk:"おとこ",wg:"men (on the toilet door)"},
 {g:"sign",k:"女",on:"ジョ",kun:"おんな",en:"woman",w:"女",wk:"おんな",wg:"women (on the toilet door)"},
 {g:"sign",k:"洗",on:"セン",kun:"あら.う",en:"wash",w:"お手洗い",wk:"おてあらい",wg:"restroom (lit. hand-washing)"},
 {g:"sign",k:"押",on:"オウ",kun:"お.す",en:"push",w:"押",wk:"おす",wg:"push (on a door)"},
 {g:"sign",k:"引",on:"イン",kun:"ひ.く",en:"pull",w:"引",wk:"ひく",wg:"pull (on a door)"},
 {g:"sign",k:"開",on:"カイ",kun:"あ.く / ひら.く",en:"open",w:"開店",wk:"かいてん",wg:"opening time"},
 {g:"sign",k:"閉",on:"ヘイ",kun:"し.まる",en:"close",w:"閉店",wk:"へいてん",wg:"closing time"},
 {g:"sign",k:"営",on:"エイ",kun:"いとな.む",en:"run a business",w:"営業中",wk:"えいぎょうちゅう",wg:"open for business"},
 {g:"sign",k:"業",on:"ギョウ",kun:"わざ",en:"business, trade",w:"営業中",wk:"えいぎょうちゅう",wg:"open for business"},
 {g:"sign",k:"準",on:"ジュン",kun:"",en:"prepare, standard",w:"準備中",wk:"じゅんびちゅう",wg:"closed for now, getting ready"},
 {g:"sign",k:"備",on:"ビ",kun:"そな.える",en:"equip, prepare",w:"準備中",wk:"じゅんびちゅう",wg:"closed for now, getting ready"},
 {g:"sign",k:"危",on:"キ",kun:"あぶ.ない",en:"danger",w:"危険",wk:"きけん",wg:"danger"},
 {g:"sign",k:"険",on:"ケン",kun:"けわ.しい",en:"steep, hazardous",w:"危険",wk:"きけん",wg:"danger"},
 {g:"sign",k:"意",on:"イ",kun:"",en:"mind, intention",w:"注意",wk:"ちゅうい",wg:"caution"},
 {g:"sign",k:"非",on:"ヒ",kun:"",en:"non-, un-",w:"非常口",wk:"ひじょうぐち",wg:"emergency exit"},
 {g:"sign",k:"常",on:"ジョウ",kun:"つね",en:"usual, always",w:"非常口",wk:"ひじょうぐち",wg:"emergency exit"},
 {g:"sign",k:"無",on:"ム",kun:"な.い",en:"nothing, without",w:"無料",wk:"むりょう",wg:"free of charge"},
 {g:"sign",k:"有",on:"ユウ",kun:"あ.る",en:"have, exist",w:"有料",wk:"ゆうりょう",wg:"paid, not free"},
 {g:"sign",k:"左",on:"サ",kun:"ひだり",en:"left",w:"左",wk:"ひだり",wg:"left"},
 {g:"sign",k:"東",on:"トウ",kun:"ひがし",en:"east",w:"東口",wk:"ひがしぐち",wg:"east exit"},
 {g:"sign",k:"西",on:"セイ",kun:"にし",en:"west",w:"西口",wk:"にしぐち",wg:"west exit"},
 {g:"sign",k:"南",on:"ナン",kun:"みなみ",en:"south",w:"南口",wk:"みなみぐち",wg:"south exit"},
 {g:"sign",k:"北",on:"ホク",kun:"きた",en:"north",w:"北口",wk:"きたぐち",wg:"north exit"},
 /* --- stations, tickets, money windows --- */
 {g:"sign",k:"駅",on:"エキ",kun:"",en:"station",w:"駅",wk:"えき",wg:"train station"},
 {g:"sign",k:"線",on:"セン",kun:"",en:"line",w:"山手線",wk:"やまのてせん",wg:"the Yamanote line"},
 {g:"sign",k:"券",on:"ケン",kun:"",en:"ticket, voucher",w:"乗車券",wk:"じょうしゃけん",wg:"passenger ticket"},
 {g:"sign",k:"精",on:"セイ",kun:"",en:"refine, exact",w:"精算",wk:"せいさん",wg:"settle the fare or bill"},
 {g:"sign",k:"算",on:"サン",kun:"",en:"calculate",w:"精算",wk:"せいさん",wg:"settle the fare or bill"},
 {g:"sign",k:"両",on:"リョウ",kun:"",en:"both, pair",w:"両替",wk:"りょうがえ",wg:"money exchange"},
 {g:"sign",k:"受",on:"ジュ",kun:"う.ける",en:"receive",w:"受付",wk:"うけつけ",wg:"reception desk"},
 {g:"sign",k:"空",on:"クウ",kun:"そら / あ.く",en:"sky, empty, vacant",w:"空港",wk:"くうこう",wg:"airport"},
 {g:"sign",k:"港",on:"コウ",kun:"みなと",en:"harbor, port",w:"空港",wk:"くうこう",wg:"airport"},
 {g:"sign",k:"到",on:"トウ",kun:"",en:"arrive",w:"到着",wk:"とうちゃく",wg:"arrival"},
 {g:"sign",k:"着",on:"チャク",kun:"つ.く / き.る",en:"arrive, wear",w:"到着",wk:"とうちゃく",wg:"arrival"},
 {g:"sign",k:"発",on:"ハツ",kun:"",en:"depart, emit",w:"出発",wk:"しゅっぱつ",wg:"departure"},
 /* --- rooms, floors, the bath --- */
 {g:"sign",k:"段",on:"ダン",kun:"",en:"step, grade",w:"階段",wk:"かいだん",wg:"stairs"},
 {g:"sign",k:"室",on:"シツ",kun:"むろ",en:"room",w:"和室",wk:"わしつ",wg:"Japanese-style room"},
 {g:"sign",k:"個",on:"コ",kun:"",en:"individual, counter for items",w:"個室",wk:"こしつ",wg:"private room"},
 {g:"sign",k:"和",on:"ワ",kun:"やわ.らぐ",en:"Japanese style, harmony",w:"和室",wk:"わしつ",wg:"Japanese-style room"},
 {g:"sign",k:"洋",on:"ヨウ",kun:"",en:"Western style, ocean",w:"洋室",wk:"ようしつ",wg:"Western-style room"},
 {g:"sign",k:"泉",on:"セン",kun:"いずみ",en:"spring (of water)",w:"温泉",wk:"おんせん",wg:"hot spring"},
 {g:"sign",k:"湯",on:"トウ",kun:"ゆ",en:"hot water",w:"男湯",wk:"おとこゆ",wg:"men's bath"},
 /* --- calendar and clock --- */
 {g:"sign",k:"年",on:"ネン",kun:"とし",en:"year",w:"今年",wk:"ことし",wg:"this year"},
 {g:"sign",k:"月",on:"ゲツ / ガツ",kun:"つき",en:"month, moon",w:"一月",wk:"いちがつ",wg:"January"},
 {g:"sign",k:"曜",on:"ヨウ",kun:"",en:"day of the week",w:"日曜日",wk:"にちようび",wg:"Sunday"},
 {g:"sign",k:"午",on:"ゴ",kun:"",en:"noon",w:"午前",wk:"ごぜん",wg:"a.m. (before noon)"},
 /* --- pharmacy and clinic --- */
 {g:"sign",k:"病",on:"ビョウ",kun:"や.む",en:"illness",w:"病院",wk:"びょういん",wg:"hospital"},
 {g:"sign",k:"院",on:"イン",kun:"",en:"institution",w:"病院",wk:"びょういん",wg:"hospital"},
 {g:"sign",k:"薬",on:"ヤク",kun:"くすり",en:"medicine",w:"薬局",wk:"やっきょく",wg:"pharmacy"},
 {g:"sign",k:"局",on:"キョク",kun:"",en:"bureau, office",w:"郵便局",wk:"ゆうびんきょく",wg:"post office"},

 /* --- the kanji your own scenes and cards are made of --- */
 {g:"app",k:"願",on:"ガン",kun:"ねが.う",en:"request, wish",w:"お願いします",wk:"おねがいします",wg:"please (the workhorse phrase)"},
 {g:"app",k:"何",on:"カ",kun:"なに / なん",en:"what, how many",w:"何名様",wk:"なんめいさま",wg:"how many people"},
 {g:"app",k:"一",on:"イチ",kun:"ひと.つ",en:"one",w:"一階",wk:"いっかい",wg:"first floor"},
 {g:"app",k:"食",on:"ショク",kun:"た.べる",en:"eat, food",w:"朝食",wk:"ちょうしょく",wg:"breakfast"},
 {g:"app",k:"時",on:"ジ",kun:"とき",en:"time, o'clock",w:"九時",wk:"くじ",wg:"nine o'clock"},
 {g:"app",k:"日",on:"ニチ",kun:"ひ / か",en:"day, sun",w:"何日",wk:"なんにち",wg:"how many days"},
 {g:"app",k:"円",on:"エン",kun:"まる.い",en:"yen, circle",w:"五百円",wk:"ごひゃくえん",wg:"500 yen"},
 {g:"app",k:"場",on:"ジョウ",kun:"ば",en:"place, grounds",w:"ゴルフ場",wk:"ゴルフじょう",wg:"golf course"},
 {g:"app",k:"番",on:"バン",kun:"",en:"number, turn, watch",w:"三番",wk:"さんばん",wg:"number three (the 3-iron, hole 3)"},
 {g:"app",k:"物",on:"ブツ",kun:"もの",en:"thing, object",w:"荷物",wk:"にもつ",wg:"luggage"},
 {g:"app",k:"大",on:"ダイ",kun:"おお.きい",en:"big",w:"大丈夫",wk:"だいじょうぶ",wg:"it's fine / no thanks"},
 {g:"app",k:"部",on:"ブ",kun:"",en:"part, section",w:"お部屋",wk:"おへや",wg:"room (部屋 reads へや, irregular)"},
 {g:"app",k:"荷",on:"カ",kun:"に",en:"load, baggage",w:"荷物",wk:"にもつ",wg:"luggage"},
 {g:"app",k:"人",on:"ジン / ニン",kun:"ひと",en:"person",w:"一人",wk:"ひとり",wg:"one person"},
 {g:"app",k:"階",on:"カイ",kun:"",en:"floor, storey",w:"二階",wk:"にかい",wg:"second floor"},
 {g:"app",k:"本",on:"ホン",kun:"もと",en:"book, origin, counter for long things",w:"基本",wk:"きほん",wg:"basic, fundamental"},
 {g:"app",k:"二",on:"ニ",kun:"ふた.つ",en:"two",w:"二階",wk:"にかい",wg:"second floor"},
 {g:"app",k:"金",on:"キン",kun:"かね",en:"gold, money",w:"現金",wk:"げんきん",wg:"cash"},
 {g:"app",k:"少",on:"ショウ",kun:"すこ.し / すく.ない",en:"few, a little",w:"少々",wk:"しょうしょう",wg:"just a moment, a little"},
 {g:"app",k:"屋",on:"オク",kun:"や",en:"shop, roof",w:"居酒屋",wk:"いざかや",wg:"izakaya"},
 {g:"app",k:"使",on:"シ",kun:"つか.う",en:"use",w:"使えますか",wk:"つかえますか",wg:"can I use it?"},
 {g:"app",k:"車",on:"シャ",kun:"くるま",en:"car, vehicle",w:"電車",wk:"でんしゃ",wg:"train"},
 {g:"app",k:"返",on:"ヘン",kun:"かえ.す",en:"return, give back",w:"返事",wk:"へんじ",wg:"a reply"},
 {g:"app",k:"払",on:"フツ",kun:"はら.う",en:"pay",w:"支払い",wk:"しはらい",wg:"payment"},
 {g:"app",k:"乗",on:"ジョウ",kun:"の.る",en:"ride, board",w:"乗り場",wk:"のりば",wg:"boarding point, taxi stand"},
 {g:"app",k:"今",on:"コン",kun:"いま",en:"now",w:"今日",wk:"きょう",wg:"today"},
 {g:"app",k:"手",on:"シュ",kun:"て",en:"hand",w:"相手",wk:"あいて",wg:"the other person"},
 {g:"app",k:"温",on:"オン",kun:"あたた.かい / あたた.める",en:"warm",w:"温めますか",wk:"あたためますか",wg:"shall I warm it up?"},
 {g:"app",k:"袋",on:"タイ",kun:"ふくろ",en:"bag, sack",w:"袋",wk:"ふくろ",wg:"bag"},
 {g:"app",k:"気",on:"キ",kun:"",en:"spirit, air, feeling",w:"天気",wk:"てんき",wg:"weather"},
 {g:"app",k:"待",on:"タイ",kun:"ま.つ",en:"wait",w:"お待ちください",wk:"おまちください",wg:"please wait"},
 {g:"app",k:"会",on:"カイ",kun:"あ.う",en:"meet, association",w:"お会計",wk:"おかいけい",wg:"the bill"},
 {g:"app",k:"後",on:"ゴ",kun:"あと / うし.ろ",en:"after, behind",w:"また後で",wk:"またあとで",wg:"see you later"},
 {g:"app",k:"行",on:"コウ",kun:"い.く",en:"go",w:"行きます",wk:"いきます",wg:"I'm going"},
 {g:"app",k:"買",on:"バイ",kun:"か.う",en:"buy",w:"買えますか",wk:"かえますか",wg:"can I buy it?"},
 {g:"app",k:"酒",on:"シュ",kun:"さけ",en:"alcohol, sake",w:"居酒屋",wk:"いざかや",wg:"izakaya"},
 {g:"app",k:"付",on:"フ",kun:"つ.く / つ.ける",en:"attach, come with",w:"受付",wk:"うけつけ",wg:"reception desk"},
 {g:"app",k:"分",on:"フン / ブン",kun:"わ.ける",en:"minute, part, divide",w:"五分",wk:"ごふん",wg:"five minutes"},
 {g:"app",k:"朝",on:"チョウ",kun:"あさ",en:"morning",w:"朝食",wk:"ちょうしょく",wg:"breakfast"},
 {g:"app",k:"打",on:"ダ",kun:"う.つ",en:"hit, strike",w:"打ちます",wk:"うちます",wg:"I'll hit (my shot)"},
 {g:"app",k:"席",on:"セキ",kun:"",en:"seat",w:"満席",wk:"まんせき",wg:"fully booked, no seats"},
 {g:"app",k:"持",on:"ジ",kun:"も.つ",en:"hold, carry",w:"持ち帰り",wk:"もちかえり",wg:"takeout"},
 {g:"app",k:"来",on:"ライ",kun:"く.る",en:"come",w:"来ました",wk:"きました",wg:"I came"},
 {g:"app",k:"僕",on:"ボク",kun:"",en:"I, me (male, casual)",w:"僕",wk:"ぼく",wg:"I (what you say to a buddy)"},
 {g:"app",k:"方",on:"ホウ",kun:"かた",en:"direction, way, person (polite)",w:"使い方",wk:"つかいかた",wg:"how to use it"},
 {g:"app",k:"煙",on:"エン",kun:"けむり",en:"smoke",w:"禁煙",wk:"きんえん",wg:"no smoking"},
 {g:"app",k:"禁",on:"キン",kun:"",en:"prohibited",w:"禁煙",wk:"きんえん",wg:"no smoking"},
 {g:"app",k:"教",on:"キョウ",kun:"おし.える",en:"teach, tell",w:"教えてください",wk:"おしえてください",wg:"please tell me"},
 {g:"app",k:"料",on:"リョウ",kun:"",en:"fee, materials",w:"無料",wk:"むりょう",wg:"free of charge"},
 {g:"app",k:"焼",on:"ショウ",kun:"や.く",en:"burn, grill",w:"焼酎",wk:"しょうちゅう",wg:"shochu"},
 {g:"app",k:"名",on:"メイ",kun:"な",en:"name",w:"名前",wk:"なまえ",wg:"name"},
 {g:"app",k:"様",on:"ヨウ",kun:"さま",en:"honorific for a person, manner",w:"何名様",wk:"なんめいさま",wg:"how many people (polite)"},
 {g:"app",k:"飲",on:"イン",kun:"の.む",en:"drink",w:"飲み放題",wk:"のみほうだい",wg:"all-you-can-drink"},
 {g:"app",k:"計",on:"ケイ",kun:"はか.る",en:"measure, total",w:"お会計",wk:"おかいけい",wg:"the bill"},
 {g:"app",k:"予",on:"ヨ",kun:"",en:"beforehand",w:"予約",wk:"よやく",wg:"reservation"},
 {g:"app",k:"約",on:"ヤク",kun:"",en:"promise, approximately",w:"予約",wk:"よやく",wg:"reservation"},
 {g:"app",k:"風",on:"フウ",kun:"かぜ",en:"wind, style",w:"お風呂",wk:"おふろ",wg:"bath"},
 {g:"app",k:"呂",on:"ロ",kun:"",en:"spine (used for its sound)",w:"お風呂",wk:"おふろ",wg:"bath"},
 {g:"app",k:"丈",on:"ジョウ",kun:"たけ",en:"length, sturdy",w:"大丈夫",wk:"だいじょうぶ",wg:"it's fine"},
 {g:"app",k:"夫",on:"フ",kun:"おっと",en:"husband, sturdy",w:"大丈夫",wk:"だいじょうぶ",wg:"it's fine"},
 {g:"app",k:"先",on:"セン",kun:"さき",en:"ahead, previous, tip",w:"お先にどうぞ",wk:"おさきにどうぞ",wg:"after you, go ahead"},
 {g:"app",k:"五",on:"ゴ",kun:"いつ.つ",en:"five",w:"五百円",wk:"ごひゃくえん",wg:"500 yen"},
 {g:"app",k:"電",on:"デン",kun:"",en:"electricity",w:"電車",wk:"でんしゃ",wg:"train"},
 {g:"app",k:"置",on:"チ",kun:"お.く",en:"put, place",w:"置いてください",wk:"おいてください",wg:"please put it there"},
 {g:"app",k:"見",on:"ケン",kun:"み.る",en:"see, look",w:"見てください",wk:"みてください",wg:"please look"},
 {g:"app",k:"所",on:"ショ",kun:"ところ",en:"place",w:"喫煙所",wk:"きつえんじょ",wg:"smoking area"},
 {g:"app",k:"満",on:"マン",kun:"み.ちる",en:"full",w:"満タン",wk:"まんタン",wg:"a full tank"},
 {g:"app",k:"冷",on:"レイ",kun:"つめ.たい / ひ.やす",en:"cold, chill",w:"冷酒",wk:"れいしゅ",wg:"cold sake"},
 {g:"app",k:"前",on:"ゼン",kun:"まえ",en:"front, before",w:"名前",wk:"なまえ",wg:"name"},
 {g:"app",k:"国",on:"コク",kun:"くに",en:"country",w:"韓国",wk:"かんこく",wg:"Korea"},
 {g:"app",k:"韓",on:"カン",kun:"",en:"Korea",w:"韓国",wk:"かんこく",wg:"Korea"},
 {g:"app",k:"頑",on:"ガン",kun:"",en:"stubborn, persist",w:"頑張ろう",wk:"がんばろう",wg:"let's give it our best"},
 {g:"app",k:"張",on:"チョウ",kun:"は.る",en:"stretch, stick out",w:"頑張ろう",wk:"がんばろう",wg:"let's give it our best"},
 {g:"app",k:"高",on:"コウ",kun:"たか.い",en:"high, expensive",w:"高いですね",wk:"たかいですね",wg:"that's expensive"},
 {g:"app",k:"機",on:"キ",kun:"",en:"machine, chance",w:"コピー機",wk:"コピーき",wg:"copier"},
 {g:"app",k:"証",on:"ショウ",kun:"あかし",en:"proof, certificate",w:"免許証",wk:"めんきょしょう",wg:"license"},
 {g:"app",k:"免",on:"メン",kun:"まぬか.れる",en:"exemption, license",w:"免税",wk:"めんぜい",wg:"duty free"},
 {g:"app",k:"税",on:"ゼイ",kun:"",en:"tax",w:"税込み",wk:"ぜいこみ",wg:"tax included"},
 {g:"app",k:"切",on:"セツ",kun:"き.る",en:"cut",w:"切手",wk:"きって",wg:"postage stamp"},
 {g:"app",k:"宅",on:"タク",kun:"",en:"house, home",w:"宅急便",wk:"たっきゅうびん",wg:"courier service"},
 {g:"app",k:"便",on:"ビン / ベン",kun:"",en:"mail, flight, convenience",w:"宅急便",wk:"たっきゅうびん",wg:"courier service"},
 {g:"app",k:"届",on:"",kun:"とど.く / とど.ける",en:"reach, deliver",w:"届きます",wk:"とどきます",wg:"it will arrive"},
 {g:"app",k:"合",on:"ゴウ",kun:"あ.う",en:"fit, match, combine",w:"合っています",wk:"あっています",wg:"that's correct"},
 {g:"app",k:"預",on:"ヨ",kun:"あず.ける",en:"entrust, deposit",w:"預けたい",wk:"あずけたい",wg:"I'd like to leave it with you"},
 {g:"app",k:"支",on:"シ",kun:"ささ.える",en:"support, branch",w:"支払い",wk:"しはらい",wg:"payment"},
 {g:"app",k:"別",on:"ベツ",kun:"わか.れる",en:"separate, another",w:"別料金",wk:"べつりょうきん",wg:"extra charge"},
 {g:"app",k:"水",on:"スイ",kun:"みず",en:"water",w:"お水",wk:"おみず",wg:"water"},
 {g:"app",k:"昼",on:"チュウ",kun:"ひる",en:"noon, daytime",w:"お昼",wk:"おひる",wg:"lunch, midday"},
 {g:"app",k:"間",on:"カン",kun:"あいだ",en:"interval, between",w:"時間",wk:"じかん",wg:"time, hours"},
 {g:"app",k:"止",on:"シ",kun:"と.まる / と.める",en:"stop",w:"止まれ",wk:"とまれ",wg:"stop (road sign)"},
 {g:"app",k:"売",on:"バイ",kun:"う.る",en:"sell",w:"売り切れ",wk:"うりきれ",wg:"sold out"},
 {g:"app",k:"強",on:"キョウ",kun:"つよ.い",en:"strong",w:"強いですね",wk:"つよいですね",wg:"it's strong (the wind)"},
 {g:"app",k:"十",on:"ジュウ",kun:"とお",en:"ten",w:"二十四時間",wk:"にじゅうよじかん",wg:"24 hours"},
 {g:"app",k:"上",on:"ジョウ",kun:"うえ / あ.げる",en:"above, up, skilled",w:"お上手",wk:"おじょうず",wg:"skillful (what they say about your swing)"},
 {g:"app",k:"盛",on:"セイ",kun:"も.る",en:"heap up, serve",w:"大盛り",wk:"おおもり",wg:"large portion"},
 {g:"app",k:"杯",on:"ハイ",kun:"さかずき",en:"cup, counter for drinks",w:"乾杯",wk:"かんぱい",wg:"cheers"},
 {g:"app",k:"込",on:"",kun:"こ.む",en:"crowded, included",w:"税込み",wk:"ぜいこみ",wg:"tax included"},
 {g:"app",k:"注",on:"チュウ",kun:"そそ.ぐ",en:"pour, focus on",w:"ご注文",wk:"ごちゅうもん",wg:"your order"},
 {g:"app",k:"私",on:"シ",kun:"わたし",en:"I, me, private",w:"私",wk:"わたし",wg:"I (the polite default)"},
 {g:"app",k:"中",on:"チュウ",kun:"なか",en:"middle, inside, in progress",w:"準備中",wk:"じゅんびちゅう",wg:"closed for now"},
 {g:"app",k:"初",on:"ショ",kun:"はじ.めて",en:"first, beginning",w:"初めて",wk:"はじめて",wg:"for the first time"},
 {g:"app",k:"疲",on:"ヒ",kun:"つか.れる",en:"get tired",w:"疲れた",wk:"つかれた",wg:"tired (plain form)"},
 {g:"app",k:"次",on:"ジ",kun:"つぎ",en:"next, order",w:"次は僕",wk:"つぎはぼく",wg:"I'm next"},
 {g:"app",k:"目",on:"モク",kun:"め",en:"eye, purpose",w:"目的",wk:"もくてき",wg:"purpose (of your visit)"},
 {g:"app",k:"泊",on:"ハク",kun:"と.まる",en:"stay overnight",w:"五泊",wk:"ごはく",wg:"five nights"},
 {g:"app",k:"申",on:"シン",kun:"もう.す",en:"say (humble), report",w:"申告",wk:"しんこく",wg:"declaration (at customs)"},
 {g:"app",k:"替",on:"タイ",kun:"か.える",en:"exchange, replace",w:"両替",wk:"りょうがえ",wg:"money exchange"},
 {g:"app",k:"帰",on:"キ",kun:"かえ.る",en:"return home",w:"帰ります",wk:"かえります",wg:"I'm heading back"},
 {g:"app",k:"事",on:"ジ",kun:"こと",en:"thing, matter",w:"返事",wk:"へんじ",wg:"a reply"},
 {g:"app",k:"近",on:"キン",kun:"ちか.い",en:"near",w:"近く",wk:"ちかく",wg:"nearby"},
 {g:"app",k:"送",on:"ソウ",kun:"おく.る",en:"send",w:"送れますか",wk:"おくれますか",wg:"can you send it?"},
 {g:"app",k:"速",on:"ソク",kun:"はや.い",en:"fast (of speed)",w:"速いですか",wk:"はやいですか",wg:"is it fast? (the greens)"},
 {g:"app",k:"追",on:"ツイ",kun:"お.う",en:"chase, add on",w:"追加",wk:"ついか",wg:"an extra, an addition"},
 {g:"app",k:"加",on:"カ",kun:"くわ.える",en:"add",w:"追加",wk:"ついか",wg:"an extra, an addition"},
 {g:"app",k:"号",on:"ゴウ",kun:"",en:"number, issue",w:"番号",wk:"ばんごう",wg:"number (locker, phone)"},
 {g:"app",k:"道",on:"ドウ",kun:"みち",en:"road, way, path",w:"この道",wk:"このみち",wg:"this road"},
 {g:"app",k:"現",on:"ゲン",kun:"あらわ.れる",en:"present, appear",w:"現金",wk:"げんきん",wg:"cash"},
 {g:"app",k:"動",on:"ドウ",kun:"うご.く",en:"move",w:"動画",wk:"どうが",wg:"video"},
 {g:"app",k:"店",on:"テン",kun:"みせ",en:"shop, store",w:"喫茶店",wk:"きっさてん",wg:"coffee shop"},
 {g:"app",k:"枚",on:"マイ",kun:"",en:"counter for flat things",w:"二枚",wk:"にまい",wg:"two sheets"},
 {g:"app",k:"早",on:"ソウ",kun:"はや.い",en:"early (of time)",w:"早めに",wk:"はやめに",wg:"a bit earlier"},
 {g:"app",k:"練",on:"レン",kun:"ね.る",en:"practice, knead",w:"練習場",wk:"れんしゅうじょう",wg:"driving range"},
 {g:"app",k:"習",on:"シュウ",kun:"なら.う",en:"learn",w:"練習",wk:"れんしゅう",wg:"practice"},
 {g:"app",k:"書",on:"ショ",kun:"か.く",en:"write",w:"領収書",wk:"りょうしゅうしょ",wg:"receipt"},
 {g:"app",k:"定",on:"テイ",kun:"さだ.める",en:"fix, determine",w:"暫定球",wk:"ざんていきゅう",wg:"provisional ball"},
 {g:"app",k:"百",on:"ヒャク",kun:"",en:"hundred",w:"五百円",wk:"ごひゃくえん",wg:"500 yen"},
 {g:"app",k:"千",on:"セン",kun:"ち",en:"thousand",w:"三千円",wk:"さんぜんえん",wg:"3,000 yen"},
 {g:"app",k:"右",on:"ウ",kun:"みぎ",en:"right",w:"右です",wk:"みぎです",wg:"it's on the right"},
 {g:"app",k:"生",on:"セイ",kun:"なま / い.きる",en:"raw, fresh, life",w:"生ビール",wk:"なまビール",wg:"draft beer"}
];
